version: '2'
services:
    gestioncra-app:
        image: gestioncra
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestioncra-mysql:3306/gestioncra?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gestioncra-mysql:
        extends:
            file: mysql.yml
            service: gestioncra-mysql
